name: Cloud Custodian Policy Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-custodian:
    runs-on: ubuntu-latest
    
    env:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install Cloud Custodian
        run: |
          python -m pip install --upgrade pip
          pip install c7n c7n-azure c7n-org
          custodian version
          c7n-org --help

      - name: Generate Subscription Inventory
        run: |
          python azuresubs.py -f subscriptions.yml
          cat subscriptions.yml

      - name: Execute Policies (Storage Account and Front Door)
        run: |

          echo "[INFO] Iniciando ejecucion de politica: Azure Front Door"
          c7n-org run -c subscriptions.yml -s output-logs -u policies/front_door.yml --debug --cache-period 0 

          echo "[INFO] Iniciando ejecucion de politica: Azure Storage Account"
          c7n-org run -c subscriptions.yml -s output-logs -u policies/storage.yml --debug --cache-period 0 

      - name: Generate Normalized Reports (Console and CSV)
        run: |
          echo "[INFO] Generando reporte: Azure Storage Account"
          c7n-org report -c subscriptions.yml -s output-logs -u policies/storage.yml \
            --field "Environment=tags.Environment" \
            | sed 's/"desa"/"Desarrollo"/g; s/"Desa"/"Desarrollo"/g; s/"DESA"/"Desarrollo"/g' \
            | sed 's/"cert"/"Certificacion"/g; s/"Cert"/"Certificacion"/g; s/"CERT"/"Certificacion"/g' \
            | tee reporte_storage.csv \
            | column -t -s ','
            
          echo ""
          echo "[INFO] Generando reporte: Azure Front Door"
          c7n-org report -c subscriptions.yml -s output-logs -u policies/front_door.yml \
            --field "Environment=tags.Environment" \
            | sed 's/"desa"/"Desarrollo"/g; s/"Desa"/"Desarrollo"/g; s/"DESA"/"Desarrollo"/g' \
            | sed 's/"cert"/"Certificacion"/g; s/"Cert"/"Certificacion"/g; s/"CERT"/"Certificacion"/g' \
            | tee reporte_front_door.csv \
            | column -t -s ','

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-custodian
          path: |
            output-logs/
            reporte_storage.csv
            reporte_front_door.csv
            st-exclude.csv